<?php

$questions = [
    ["Sinhala questions", "k_1"],
    ["Use precision machines to build custom metal parts", "k_2"],
    ["Analyze the structure of molecules", "q_1"],
    ["Do scientific experiments", "q_2"],
    ["Design a magazine cover", "m_1"],
    ["Paint a portrait", "m_2"],
    ["Teach social skills to disabled children", "n_1"],
    ["Teach adults to read", "n_2"],
    ["Coordinate a business conference", "o_1"],
    ["Plan a marketing strategy for a new company", "o_2"],
    ["Track monthly expenses for a company", "p_1"],
    ["Review financial records for accuracy", "p_2"],
    ["Install a hardwood floor", "k_3"],
    ["Repair an air conditioning system", "k_4"],
    ["Research the properties of nuclear energy", "q_3"],
    ["Research a new medicine", "q_4"],
    ["Design a greeting card", "m_3"],
    ["Illustrate a children’s book", "m_4"],
    ["Help a disabled person with their daily routine", "n_3"],
    ["Tutor a child with a learning disability", "n_4"],
    ["Negotiate business partnerships", "o_3"],
    ["Motivate employees to achieve success", "o_4"],
    ["Keep payroll records", "p_3"],
    ["Use spreadsheets to organize financial data", "p_4"],
    ["Install an alarm system in a building", "k_5"],
    ["Install kitchen cabinets", "k_6"],
    ["Look at cells through a microscope", "q_5"],
    ["Work in a chemistry lab", "q_6"],
    ["Design magazine ads", "m_5"],
    ["Write a script for a television show", "m_6"],
    ["Counsel a person recovering from drug addiction", "n_5"],
    ["Counsel a person with depression", "n_6"],
    ["Hire and fire employees", "o_5"],
    ["Close an important business deal", "o_6"],
    ["Check tax returns for errors", "p_5"],
    ["Calculate the cost of an insurance claim", "p_6"],
    ["Build a stone wall", "k_7"],
    ["Operate a bulldozer", "k_8"],
    ["Analyze soil samples for pollution", "q_7"],
    ["Study a fault line to predict earthquakes", "q_8"],
    ["Design a billboard advertisement", "m_7"],
    ["Edit a movie", "m_8"],
    ["Plan educational games for preschool children", "n_7"],
    ["Plan activities for elderly people", "n_8"],
    ["Lead a team", "o_7"],
    ["Start a new business", "o_8"],
    ["Calculate the cost of a construction project", "p_7"],
    ["Help customers fill out loan applications", "p_8"],
    ["Take apart a car engine", "k_9"],
    ["Inspect a roof for leaks", "k_1_0"],
    ["Do laboratory tests to diseases", "q_9"],
    ["Research heat esistant materials for airplane engines", "q_1_0"],
    ["Compose a song", "m_9"],
    ["Write a poem", "m_1_0"],
    ["Help diabetic patients plan a proper diet plan", "n_9"],
    ["Help a needy family find appropriate housing", "n_1_0"],
    ["Give a speech in front of many people", "o_9"],
    ["Persuade others to my point of view", "o_1_0"],
    ["Collect tax payments", "p_9"],
    ["Develop a budget for a city government", "p_1_0"]
    ];

$primary = [
    ['BUILDING',
    'Builders'],
    ['THINKING',
    'Thinkers'],
    ['CREATING',
    'Creators'],
    ['HELPING',
    'Helpers'],
    ['PERSUADING',
    'Persuaders'],
    ['ORGANIZING',
    'Organizers']
];

$paragraph = [
    ['As a Builder, you prefer physical work that uses your hands and body and gives you a tangible
    result for your efforts. You prefer working with concrete objects, not abstract concepts. You may be drawn to work
    with tools, machines, plants, or animals. You like to be outdoors and be physically active throughout the day.',
    'Because you are a Builder, you will prefer a career that allows you to use and hone your hands-on
    skills. You enjoy learning to construct, craft, repair, maintain, and tinker. You like creating practical things and
    fixing necessary systems.',
    'Builders tend to be pragmatic, down-to-earth people who take a “just do it” approach to life.
    Builders often dislike having to explain or discuss their work with others, preferring instead to jump in and simply
    get it done.',
    'Builders like their work best when they can see a real, physical result of their efforts. As a
    Builder, your primary career goal will be to discover a job where you can use your physical or mechanical skills to
    take useful, observable action on the world around you.'],
    ['As a Thinker, you enjoy working with ideas and theories. You want to solve complex problems through
    rational, logical analysis. You are fascinated by the sciences and the process of discovering new information about
    the world around you. You are drawn to environments where research is the focus, such as academia or scientific
    industries. You want to explore and discover new ideas in your work.',
    'Because you are a Thinker, you will prefer a career that primarily utilizes your intellectual
    powers. You want to learn, discover, research, examine, and analyze. You will strive to gain a deep understanding of
    your field and use your expertise to devise innovative new solutions.',
    'Thinkers tend to be introspective, serious people who have a lifelong love of learning. They often
    excel in school and are usually confident in their intelligence. They may relate to others by discussing ideas and
    shy away from personal disclosures.',
    'Thinkers like their work best when they can continually grow their intellect and improve their
    understanding of the laws of the universe. As a Thinker, your primary career goal will be to find a job that allows
    you to use your powers of rational analysis to form theories, test hypotheses, gather data, and make exciting new
    discoveries.'],
    ['As a Creator, your primary drive is to use your creative talents and express yourself artistically
    through your work. You have a strong aesthetic sense and seek work that allows you to connect with experiences that
    stimulate the senses. You enjoy art, music, drama, dance, architecture, and literature, and seek work that exposes
    you to various art forms and allows you to communicate your own vision among them.',
    'Because you are a Creator, you will seek a career that allows you a great deal of freedom to
    express yourself. You want to imagine, envision, experiment, and create. You want to develop your own unique point
    of view and see it manifest in your chosen field.',
    'Creators tend to be idealistic, artistic people who are drawn to cultural experiences. They often
    have many artistic interests and seek out novel forms of expression, from modern art museums to experimental dance.
    They tend to be unconventional and interested in the offbeat and unusual.',
    'Creators like their work best when they can be free of rules and regulations, and follow their
    inspiration to create something original. As a Creator, your primary career goal will be to decide on the best
    outlet for your artistic talent and creative expression, and then to create a plan for channeling your inspiration
    into a profitable career.'],
    ['As a Helper, you strive to dedicate your work life to serving, caring for, and inspiring others.
    You are highly attuned to the needs of the people around you and gain satisfaction from attending to those needs.
    You are driven by values in your work, and motivated by an aspiration to make the world a better place.',
    'Because you are a Helper, it will be essential that you have a job that allows you to relate
    closely with other people. You want to connect with others and feel that you have been of service to them. You may
    especially prefer to work with vulnerable people, like children, the sick, or the elderly.',
    'Helpers tend to be warm, empathetic people. They are typically friendly and approachable, and put
    others at ease. Helpers are often found listening to other people’s stories and trying to coach them through their
    problems. They are often selfless and may put their own needs aside in the service of others.',
    'Helpers like their work best when it connects deeply with their values and makes them feel that
    they are making a difference in the world. As a Helper, your primary goal will be to understand what is important to
    you, and decide how you can best manifest your ideals in your chosen career path.'],
    ['As a Persuader, you are driven to lead, influence, motivate, and direct other people. You are
    interested in making your mark on the world by impacting the perspectives and decisions of others. You enjoy feeling
    powerful and important, and want to lead the way.',
    'Because you are a Persuader, you will often gravitate to roles that allow you to sell other people
    on products, projects, or initiatives. You will find a natural home in the business world, but will enjoy any role
    where you can set a course of action and use your ingenuity and influence to achieve your goals. You may feel drawn
    to entrepreneurship and enjoy the risk inherent in starting a new venture.',
    'Persuaders tend to be natural salespeople with a high energy level and enthusiasm for engaging with
    others. They are typically good at developing rapport with others, although they may overwhelm some with their
    aggressive drive. They are typically competitive, goal-oriented, and ambitious.',
    'Persuaders like their work best when they can chase exciting goals, promote new ideas, and close
    important deals. As a Persuader, your primary career goal will be to find a job where you can take the lead to start
    and carry out initiatives, act quickly and decisively to set a course, and use your charisma to influence others.'],
    ['As an Organizer, you like to work with data, processes, and systems. You enjoy putting things in
    order and completing tasks in a systematic fashion. You appreciate a structured work environment where rules,
    policies, and standard procedures are clear and well enforced.',
    'Because you are an Organizer, you are interested in keeping orderly systems in place. You will
    often enjoy office and administrative work, especially working with systems, records, and files. You like to
    maintain structure and enforce the rules, and want to work in a well organized and predictable environment.',
    'Organizers are detail-oriented and responsible people with an appreciation for structure and order.
    They typically take things literally and have little tolerance for sloppiness or people who try to bend the rules.
    They are cautious and careful and typically dislike taking risks.',
    'Organizers like their work best when they can carefully systematize processes to work toward
    well-defined goals. As an Organizer, your primary career goal will be to find a job where you can focus on the
    details and create reliable systems to produce predictable, precise results.']
];

$top_job_tasks = [
    ['Building',
    'Repairing',
    'Taking Action',
    'Using Machines',
    'Using Tools'],
    ['Researching',
    'Experimenting',
    'Theorizing',
    'Analyzing',
    'Problem Solving'],
    ['Creating Art',
    'Writing',
    'Interpreting',
    'Designing',
    'Expressing Ideas'],
    ['Counseling',
    'Assisting',
    'Advising',
    'Teaching',
    'Providing Service'],
    ['Managing',
    'Deciding',
    'Strategizing',
    'Selling',
    'Motivating'],
    ['Filing',
    'Calculating',
    'Processing',
    'Systematizing',
    'Following Procedures']
];

$core_values = [
    ['Practicality',
    'Productivity',
    'Structure',
    'Independence',
    'Physical Skill'],
    ['Discovery',
    'Understanding',
    'Logic',
    'Independence',
    'Intellect'],
    ['Individuality',
    'Creativity',
    'Originality',
    'Freedom',
    'Flexibility'],
    ['Cooperation',
    'Service',
    'Altruism',
    'Connection',
    'Compassion'],
    ['Influence',
    'Leadership',
    'Risk-Taking',
    'Achievement',
    'Initiative'],
    ['Structure',
    'Order',
    'Clarity',
    'Precision',
    'Attention to Detail']
];

$key_personality_traits = [
    ['Realistic',
    'Sensible',
    'Mechanical',
    'Traditional',
    'Down-to-earth'],
    ['Intellectual',
    'Curious',
    'Logical',
    'Analytical',
    'Scholarly'],
    ['Independent',
    'Intuitive',
    'Sensitive',
    'Imaginative',
    'Spontaneous'],
    ['Compassionate',
    'Patient',
    'Helpful',
    'Friendly',
    'Generous'],
    ['Assertive',
    'Energetic',
    'Confident',
    'Ambitious',
    'Adventurous'],
    ['Orderly',
    'Precise',
    'Detail-Oriented',
    'Conservative',
    'Thorough']
];

$sample_jobs = [
    ['Police Officer or Detective',
    'Pilot',
    'Electrician',
    'Carpenter',
    'Auto Mechanic',
    'Building Inspector',
    'Machinist',
    'Civil Engineer',
    'Athlete or Coach'],
    ['Physician',
    'Mathematician',
    'Computer Software Engineer',
    'Chemist',
    'Environmental Scientist',
    'Biological Scientist',
    'Management Consultant or Analyst',
    'Economist',
    'Pharmacist'],
    ['Fashion Designer',
    'Art Director',
    'Graphic Designer',
    'Writer',
    'Musician or Singer',
    'Interior Designer',
    'Landscape Architect',
    'Photographer',
    'Reporter'],
    ['Teacher',
    'Child Care Worker',
    'Physical Therapist',
    'Nurse',
    'Massage Therapist',
    'Health Educator',
    'Physician Assistant',
    'Occupational Therapist',
    'Speech-Language Pathologist'],
    ['Executive',
    'Attorney',
    'Public Relations Specialist',
    'Financial Manager',
    'Personal Financial Advisor',
    'Buyer or Purchasing Agent',
    'Real Estate Agent or Broker',
    'Securities Broker',
    'Health Services Manager'],
    ['Accountant or Auditor',
    'Actuary',
    'Budget Analyst',
    'Paralegal',
    'Medical Transcriptionist',
    'Financial Analyst',
    'Administrative Assistant',
    'Cost Estimator',
    'Court Reporter']
];

$career_fields = [
    ['Construction',
    'Mechanics',
    'Transportation & Distribution',
    'Military',
    'Athletics',
    'Farming or Ranching',
    'Manufacturing and Industry',
    'Maintenance and Repair',
    'Food Preparation'],
    ['Physical Science',
    'Life Science',
    'Medicine and Health Sciences',
    'Statistics or Applied Mathematics',
    'Computer Software or Hardware Development',
    'Medical or Pharmaceutical Research',
    'Social Science',
    'Engineering',
    'Architecture'],
    ['Fine Arts',
    'Craft Arts',
    'Performing Arts',
    'Design',
    'Architecture',
    'Writing and Communications',
    'Film and Media',
    'Public Relations',
    'Arts Education'],
    ['Counseling and Coaching',
    'Social Service',
    'Personal Care and Service',
    'Health Care',
    'Human Resources',
    'Education',
    'Management'],
    ['Sales',
    'Marketing',
    'Entrepreneurship',
    'Management',
    'Public Relations',
    'Legal',
    'Politics',
    'Real Estate'],
    ['Administration',
    'Banking and Finance',
    'Accounting',
    'Office Management',
    'Computers and Technology',
    'Engineering',
    'Law Enforcement',
    'Military']
];

$areas_of_study = [
    ['Physical Education or Exercise Science',
    'Construction Management',
    'Engineering',
    'Agriculture',
    'Environmental Science',
    'Food Science',
    'Forestry',
    'Construction, Maintenance or Repair',
    'Culinary Arts'],
    ['Chemistry',
    'Physics',
    'Biology',
    'Other Physical or Life Sciences',
    'Computer Science',
    'Medical Science',
    'Social Sciences',
    'Engineering',
    'Mathematics'],
    ['Fine Arts',
    'Drama',
    'Music',
    'Dance',
    'Graphic Design',
    'Industrial Design',
    'English',
    'Foreign Language',
    'Creative Writing'],
    ['Social Work',
    'Psychology',
    'Counseling',
    'Education',
    'Child Development',
    'Gerontology',
    'Medical Sciences',
    'Nursing'],
    ['Business Administration',
    'Marketing or Advertising',
    'Hospitality',
    'Real Estate',
    'Political Science',
    'Communications',
    'Law',
    'Organizational Psychology'],
    ['Business Administration',
    'Accounting or Actuarial Science',
    'Finance',
    'Law',
    'Criminal Justice',
    'Mathematics or Statistics',
    'Information Systems',
    'Engineering',
    'Computer Science']
];

$core_needs = [
    ['Use my hands and body to do something useful',
    'Learn how to use tools, machines, and practical objects',
    'Get outdoors regularly and/or have a connection to nature',
    'Have a physical, tangible product to show for my efforts'],
    ['Use my intellect and intelligence to develop innovative solutions',
    'Research and learn to expand my knowledge and understanding',
    'Explore and discover interesting ideas',
    'Analyze information to solve complex problems'],
    ['Use my creative talents to do something original and unique to me',
    'Express my ideas, feelings and experiences',
    'Experience my senses through art, design, music, drama, or other aesthetic media',
    'Follow my inspiration to create what is authentic to me'],
    ['See the positive impact of my work on other people’s lives',
    'Help people grow, develop, learn, and thrive',
    'Empathize with others to understand their needs',
    'Use my skills and abilities to make the world a better and more caring place'],
    ['Use my charisma and powers of persuasion to motivate and influence other people',
    'Set exciting goals and take risks to achieve success',
    'Increase my power and standing within my field',
    'Promote novel ideas and impact key decisions to make my mark on the world'],
    ['Use my organizational skills to maintain rational, orderly systems',
    'Work within rules and expectations',
    'Follow clear processes to achieve measured outcomes',
    'Ensure correct and accurate results']
];

$prefered_tasks = [
    ['Working with tools or machines',
    'Working with plants or animals',
    'Repairing or maintaining things, especially mechanical systems',
    'Building, constructing, or crafting things',
    'Being athletic or physical',
    'Making something tangible, practical and useful'],
    ['Researching scientific principles and theories',
    'Gathering and analyzing data',
    'Developing and testing hypotheses',
    'Using logic and reason to form conclusions',
    'Reading and learning to increase knowledge and understanding',
    'Applying expertise to devise innovative solutions'],
    ['Working with forms, colors, patterns, or other visual elements',
    'Working with aesthetic or expressive media like dance, music, or drama',
    'Creating a visually appealing presentation or design',
    'Coming up with an original idea with few or no guidelines to follow',
    'Working on what inspires you at the moment, rather than a predetermined task',
    'Being imaginative, creative, and original'],
    ['Caring for others’ personal needs',
    'Educating or training people',
    'Counseling people on their personal issues',
    'Looking after vulnerable people, including the sick, very young, or very old',
    'Helping others grow and develop',
    'Being supportive and sympathetic'],
    ['Selling products or services',
    'Leading or managing a team',
    'Pitching ideas or initiatives',
    'Starting a new business or other venture',
    'Speaking in front of groups of people',
    'Influencing people to your way of thinking'],
    ['Managing data, files, or other forms of information',
    'Keeping things in order',
    'Developing organizational systems',
    'Following clear procedures',
    'Ensuring accuracy and correctness',
    'Maintaining efficient and well-ordered processe']
];

$key_questions = [
    ['Will this career allow me to be active throughout the day?',
    'Will I learn and use practical skills in this career?',
    'Will this career allow me to do plenty of hands-on work?'],
    ['Will this career allow me to regularly learn new things and explore new ideas?',
    'Will this career stimulate my mind and intellect?',
    'Will this career connect me with ideas, theories, and/or fields of thought that interest me?',
    'Will this career let me improve my understanding of how the world works?'],
    ['Will this career allow me to come up with my own unique and original way of doing things?',
    'Will this career allow me to be authentic and true to myself on the job?',
    'Does this career take advantage of my creative talents?',
    'Will this career put me in environments which are aesthetically pleasing and stimulating to the senses?'],
    ['Does this career allow me to see the positive impact of my work on other people?',
    'Can I show my caring, sensitive side in this career?',
    'Does this career connect with my values and allow me to change the world for the better?',
    'Will I feel that I’m doing important, meaningful work in this career?'],
    ['Will this career allow me to influence and motivate other people?',
    'Will I feel powerful and important in this career?',
    'Will this career allow me to take risks and pursue exciting achievements?',
    'Will this career give me a platform to share my ideas and persuade other people to my point of view?'],
    ['Will this career allow me to use my organizational skills?',
    'Will I be able to identify and follow clear processes and procedures in this career?',
    'Will I be working with orderly, logical systems in this career?',
    'Will my success in this career depend on my accuracy, correctness, and ability to follow specific instructions?']
];
?>