# build, test, and ftp deploy a jekyll site
name: ci:deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      baseurl: ''
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: install
        run: gem install bundler && bundle
      - name: build
        run: bundle exec rake build
      - name: test
        run: bundle exec rake test
      - name: deploy
        uses: samkirkland/ftp-deploy-action@4.0.0
        with:
          server: ${{secrets.ftp_server}}
          username: ${{secrets.ftp_username}}
          password: ${{secrets.ftp_password}}
        
